### ISSUE TITLE
学长您好，请问您还有COAE2016任务3的数据集或者解码密码吗？ 谢谢了

### ISSUE THREAD

**Issue by wishprophet** [Sewens/COAE2016#3]
学长您好，我现在做关系抽取相关的研究学习，和COAE2016任务3比较类似，但是任务3的数据集现在只在[官网上](http://ccir2016.ccnl.scut.edu.cn/caoe_test.php)找到了压缩包，没有解压密码，如果您还有解压后的数据集，希望您发给我一份，或者告知解压密码，万分感谢！本人邮箱：ling_mekansm@163.com **再次感谢！**

**Comment by Sewens** [comment]
我找一下。

**Comment by AaronWhite95** [comment]
> 学长您好，我现在做关系抽取相关的研究学习，和COAE2016任务3比较类似，但是任务3的数据集现在只在[官网上](http://ccir2016.ccnl.scut.edu.cn/caoe_test.php)找到了压缩包，没有解压密码，如果您还有解压后的数据集，希望您发给我一份，或者告知解压密码，万分感谢！本人邮箱：[ling_mekansm@163.com](mailto:ling_mekansm@163.com) **再次感谢！**

请问您现在拿到密码了吗，能否分享一下呢

**Comment by wishprophet** [comment]
> > 学长您好，我现在做关系抽取相关的研究学习，和COAE2016任务3比较类似，但是任务3的数据集现在只在[官网上](http://ccir2016.ccnl.scut.edu.cn/caoe_test.php)找到了压缩包，没有解压密码，如果您还有解压后的数据集，希望您发给我一份，或者告知解压密码，万分感谢！本人邮箱：[ling_mekansm@163.com](mailto:ling_mekansm@163.com) **再次感谢！**
> 
> 请问您现在拿到密码了吗，能否分享一下呢

并没有。。

**Comment by Sewens** [comment]
我找了一下，当初参赛的是任务二，手头只有任务二的数据。

**Comment by lfb637** [comment]
> 我找了一下，当初参赛的是任务二，手头只有任务二的数据。

您好，数据能共享吗

**Comment by Lynne515** [comment]
> 学长您好，我现在做关系抽取相关的研究学习，和COAE2016任务3比较类似，但是任务3的数据集现在只在[官网上](http://ccir2016.ccnl.scut.edu.cn/caoe_test.php)找到了压缩包，没有解压密码，如果您还有解压后的数据集，希望您发给我一份，或者告知解压密码，万分感谢！本人邮箱：ling_mekansm@163.com **再次感谢！**

您好请问有拿到数据么，可以麻烦分享一下么，加密的压缩包也行😭

**Comment by roclins** [comment]
任务三，github有人公开了！！！！指路

**Comment by roclins** [comment]
https://github.com/Lynne515/COAE2016task3

**Comment by wishprophet** [comment]
您好，我已收到你的邮件。
